# Generated by Django 3.0.2 on 2020-02-12 03:15

from django.db import migrations, models
import django.db.models.deletion
import inventory.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id_kategori', models.CharField(default=inventory.models.auto_id_kategori, editable=False, max_length=12, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=35)),
                ('user_updated', models.CharField(blank=True, max_length=35)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Ruang',
            fields=[
                ('id_ruang', models.CharField(default=inventory.models.auto_id_ruang, editable=False, max_length=12, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=35)),
                ('user_updated', models.CharField(blank=True, max_length=35)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Satker',
            fields=[
                ('id_satker', models.CharField(default=inventory.models.auto_id_satker, editable=False, max_length=12, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=35)),
                ('user_updated', models.CharField(blank=True, max_length=35)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tempat',
            fields=[
                ('id_tempat', models.CharField(default=inventory.models.auto_id_tempat, editable=False, max_length=12, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=35)),
                ('user_updated', models.CharField(blank=True, max_length=35)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, editable=False)),
                ('id_ruang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Ruang')),
            ],
        ),
        migrations.AddField(
            model_name='ruang',
            name='id_satker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Satker'),
        ),
        migrations.CreateModel(
            name='Barang',
            fields=[
                ('id_barang', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=35)),
                ('jenis', models.CharField(max_length=20)),
                ('jumlah', models.PositiveIntegerField()),
                ('jumlah_b', models.PositiveIntegerField()),
                ('jumlah_rr', models.PositiveIntegerField()),
                ('jumlah_rb', models.PositiveIntegerField()),
                ('jumlah_hl', models.PositiveIntegerField()),
                ('satuan', models.CharField(max_length=20)),
                ('nilai_barang', models.DecimalField(decimal_places=0, max_digits=20)),
                ('tgl_pengadaan', models.DateTimeField()),
                ('keterangan', models.TextField(blank=True)),
                ('in_transaction', models.BooleanField(default=False)),
                ('barcode', models.CharField(max_length=40, null=True)),
                ('user_updated', models.CharField(blank=True, max_length=35)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, editable=False)),
                ('id_kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Kategori')),
                ('id_tempat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Tempat')),
            ],
        ),
    ]
