# Generated by Django 3.0.2 on 2020-01-23 04:14

from django.db import migrations, models
import django.db.models.deletion
import inventory.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tempat',
            fields=[
                ('id_tempat', models.CharField(default=inventory.models.auto_id_tempat, editable=False, max_length=8, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=35)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Barang',
            fields=[
                ('id_barang', models.CharField(default=inventory.models.auto_id_barang, editable=False, max_length=8, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=35)),
                ('jenis', models.CharField(max_length=20)),
                ('jumlah', models.IntegerField()),
                ('satuan', models.CharField(max_length=20)),
                ('nilai_barang', models.DecimalField(decimal_places=0, max_digits=20)),
                ('satker', models.CharField(max_length=35)),
                ('tgl_pengadaan', models.DateTimeField()),
                ('keterangan', models.TextField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, editable=False)),
                ('tempat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Tempat')),
            ],
        ),
    ]
