# Generated by Django 3.0.2 on 2020-01-14 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaksi',
            name='id_barang',
            field=models.ForeignKey(default='000001', on_delete=django.db.models.deletion.CASCADE, to='inventory.Barang'),
            preserve_default=False,
        ),
    ]
