# Generated by Django 3.0.2 on 2020-02-12 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barang',
            name='barcode',
            field=models.CharField(blank=True, default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='barang',
            name='jumlah_b',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='barang',
            name='jumlah_hl',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='barang',
            name='jumlah_rb',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='barang',
            name='jumlah_rr',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
