# Generated by Django 3.0.2 on 2020-01-20 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barang',
            name='jenis',
            field=models.CharField(choices=[('Inventaris', 'Inventaris'), ('Modal', 'Modal'), ('Persediaan', 'Persediaan')], default='Pak', max_length=20),
        ),
    ]
