# Generated by Django 3.0.2 on 2020-02-04 14:09

from django.db import migrations, models
import inventory.models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20200204_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barang',
            name='barcode',
            field=models.CharField(default=inventory.models.auto_barcode, editable=False, max_length=40),
        ),
    ]
