# Generated by Django 3.0.2 on 2020-01-09 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20200109_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barang',
            name='nilai_barang',
            field=models.DecimalField(decimal_places=0, max_digits=20),
        ),
    ]
