# Generated by Django 3.0.2 on 2020-02-12 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20200212_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barang',
            name='barcode',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='barang',
            name='jumlah_b',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='barang',
            name='jumlah_hl',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='barang',
            name='jumlah_rb',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='barang',
            name='jumlah_rr',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
