# Generated by Django 3.0.2 on 2020-02-04 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20200204_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='barang',
            name='image',
            field=models.ImageField(blank=True, upload_to='img'),
        ),
    ]
