# Generated by Django 3.0.2 on 2020-01-12 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20200109_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barang',
            name='jenis',
            field=models.CharField(choices=[('Inventaris', 'Inventaris'), ('Modal', 'Modal'), ('Persediaan', 'Persediaan')], max_length=20),
        ),
        migrations.AlterField(
            model_name='barang',
            name='satuan',
            field=models.CharField(choices=[('Pak', 'Pak'), ('Buah', 'Buah'), ('Kotak', 'Kotak')], max_length=20),
        ),
    ]
