# Generated by Django 3.0.2 on 2020-01-20 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20200120_0211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barang',
            name='jenis',
            field=models.CharField(choices=[(0, 'Inventaris'), (1, 'Modal'), (2, 'Persediaan')], default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='barang',
            name='satuan',
            field=models.CharField(choices=[(0, 'Pak'), (1, 'Buah'), (2, 'Kotak')], default=0, max_length=20),
        ),
    ]
