# Generated by Django 3.0.2 on 2020-01-20 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20200120_0213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barang',
            name='jenis',
            field=models.CharField(choices=[('Inventaris', 'Inventaris'), ('Modal', 'Modal'), ('Persediaan', 'Persediaan')], default='Inventaris', max_length=20),
        ),
        migrations.AlterField(
            model_name='barang',
            name='satuan',
            field=models.CharField(choices=[('Pak', 'Pak'), ('Buah', 'Buah'), ('Kotak', 'Kotak')], default='Pak', max_length=20),
        ),
    ]
