# Generated by Django 3.0.2 on 2020-02-04 14:44

from django.db import migrations, models
import inventory.models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_remove_barang_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barang',
            name='barcode',
            field=models.CharField(blank=True, default=inventory.models.auto_barcode, max_length=40),
        ),
    ]
