# Generated by Django 3.0.2 on 2020-01-20 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20200120_0215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barang',
            name='jenis',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='barang',
            name='jumlah',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='barang',
            name='keterangan',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='barang',
            name='satuan',
            field=models.CharField(max_length=20),
        ),
    ]
