# Generated by Django 3.0.2 on 2020-03-19 03:02

from django.db import migrations, models
import django.db.models.deletion
import reports.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('satker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mutasi',
            fields=[
                ('id_mutasi', models.CharField(default=reports.models.auto_id, editable=False, max_length=13, primary_key=True, serialize=False)),
                ('id_barang', models.CharField(max_length=10)),
                ('nama_barang', models.CharField(max_length=30)),
                ('kategori', models.CharField(max_length=30)),
                ('tgl_mutasi', models.DateTimeField()),
                ('nilai_barang', models.PositiveIntegerField()),
                ('jumlah_awal', models.PositiveIntegerField()),
                ('masuk', models.PositiveIntegerField()),
                ('keluar', models.PositiveIntegerField()),
                ('user_updated', models.CharField(blank=True, max_length=35)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, editable=False)),
                ('id_satker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='satker.Satker')),
            ],
        ),
    ]
