# Generated by Django 3.0.2 on 2020-01-31 09:01

from django.db import migrations, models
import django.db.models.deletion
import reports.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mutasi',
            fields=[
                ('id_mutasi', models.CharField(default=reports.models.auto_id, editable=False, max_length=13, primary_key=True, serialize=False)),
                ('jenis', models.CharField(max_length=15)),
                ('tgl_mutasi', models.DateTimeField()),
                ('jumlah', models.PositiveIntegerField()),
                ('user_updated', models.CharField(blank=True, max_length=35)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, editable=False)),
                ('id_barang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Barang')),
                ('id_satker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Satker')),
            ],
        ),
    ]
