# Generated by Django 3.0.2 on 2020-02-12 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mutasi',
            name='kategori',
            field=models.CharField(default='Alat Tulis', max_length=30),
            preserve_default=False,
        ),
    ]
