# Generated by Django 3.0.2 on 2020-02-01 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mutasi',
            old_name='jumlah_mutasi',
            new_name='keluar',
        ),
        migrations.RemoveField(
            model_name='mutasi',
            name='jenis',
        ),
        migrations.AddField(
            model_name='mutasi',
            name='masuk',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
