# Generated by Django 3.0.2 on 2020-02-02 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auto_20200202_0107'),
    ]

    operations = [
        migrations.AddField(
            model_name='mutasi',
            name='id_barang',
            field=models.CharField(default='0000001', max_length=10),
            preserve_default=False,
        ),
    ]
