# Generated by Django 3.0.2 on 2020-02-02 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_mutasi_id_barang'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mutasi',
            old_name='jumlah_sebelum',
            new_name='jumlah_awal',
        ),
    ]
