# Generated by Django 3.0.2 on 2020-01-23 04:14

from django.db import migrations, models
import django.db.models.deletion
import transaksi.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id_user', models.CharField(default=transaksi.models.auto_id_user, editable=False, max_length=8, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=35)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaksi',
            fields=[
                ('id_transaksi', models.CharField(default=transaksi.models.auto_id_transaksi, editable=False, max_length=13, primary_key=True, serialize=False)),
                ('transaksi', models.CharField(max_length=13)),
                ('tgl_pengambilan', models.DateTimeField()),
                ('tgl_kembali', models.DateTimeField(blank=True)),
                ('jumlah', models.PositiveIntegerField()),
                ('keterangan', models.TextField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id_barang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Barang')),
                ('pengguna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaksi.Users')),
            ],
        ),
    ]
