# Generated by Django 3.0.2 on 2020-01-23 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaksi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaksi',
            name='slug',
            field=models.SlugField(blank=True, editable=False),
        ),
    ]
