# Generated by Django 3.0.2 on 2020-03-19 03:02

from django.db import migrations, models
import django.db.models.deletion
import satker.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ruang',
            fields=[
                ('id_ruang', models.CharField(default=satker.models.auto_id_ruang, editable=False, max_length=12, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=35)),
                ('is_used', models.BooleanField(default=False)),
                ('user_updated', models.CharField(blank=True, max_length=35)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Satker',
            fields=[
                ('id_satker', models.CharField(default=satker.models.auto_id_satker, editable=False, max_length=12, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=35)),
                ('is_used', models.BooleanField(default=False)),
                ('user_updated', models.CharField(blank=True, max_length=35)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tempat',
            fields=[
                ('id_tempat', models.CharField(default=satker.models.auto_id_tempat, editable=False, max_length=12, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=35)),
                ('is_used', models.BooleanField(default=False)),
                ('user_updated', models.CharField(blank=True, max_length=35)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, editable=False)),
                ('id_ruang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='satker.Ruang')),
            ],
        ),
        migrations.AddField(
            model_name='ruang',
            name='id_satker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='satker.Satker'),
        ),
    ]
